DROP TABLE CUSTOM.CUST_CDLICKEY CASCADE CONSTRAINTS;

CREATE TABLE CUSTOM.CUST_CDLICKEY
(
	MODULE_ID					VARCHAR2(50) NOT NULL	,
	SUB_MODULE_ID				VARCHAR2(50) NOT NULL	,
	LICENSE_KEY					VARCHAR2(500)			,
	ENTITY_CRE_FLG				CHAR(1)					,
	DEL_FLG						CHAR(1)					,
	LCHG_USER_ID				VARCHAR2(15)			,
	LCHG_TIME					DATE					,
	RCRE_USER_ID				VARCHAR2(15)			,
	RCRE_TIME					DATE					,
	BANK_ID						VARCHAR2(8)	NOT NULL
)
;


CREATE UNIQUE INDEX CUSTOM.IDX_CUST_CDLICKEY ON CUSTOM.CUST_CDLICKEY
(MODULE_ID,SUB_MODULE_ID,BANK_ID);


DROP SYNONYM TBAUTIL.C_CDLICKEY;

CREATE OR REPLACE SYNONYM TBAUTIL.C_CDLICKEY FOR CUSTOM.CUST_CDLICKEY;


DROP SYNONYM TBAGEN.C_CDLICKEY;

CREATE OR REPLACE SYNONYM TBAGEN.C_CDLICKEY FOR CUSTOM.CUST_CDLICKEY;


DROP SYNONYM TBAADM.C_CDLICKEY;

CREATE OR REPLACE SYNONYM TBAADM.C_CDLICKEY FOR CUSTOM.CUST_CDLICKEY;


DROP SYNONYM CUSTOM.C_CDLICKEY;

CREATE OR REPLACE SYNONYM CUSTOM.C_CDLICKEY FOR CUSTOM.CUST_CDLICKEY;


GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.CUST_CDLICKEY TO TBAADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.CUST_CDLICKEY TO TBAGEN;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.CUST_CDLICKEY TO TBAUTIL;
