CREATE OR REPLACE VIEW &customSchemaName..CUSTOM_CMMSG_VIEW AS 
	SELECT &msgIdColumn AS MSG_ID,'INFENG' AS LANG_CODE,&msgLiteralColumn AS MSG_LITERAL,&altMsgLiteral AS ALT_MSG_LITERAL, &delFlgColumn AS DEL_FLG
	FROM &cmmsgTblName;
GRANT SELECT, INSERT, UPDATE, DELETE ON &customSchemaName..CUSTOM_CMMSG_VIEW TO TBAADM,TBAGEN,TBAUTIL;
